---
title: "Instruction"
author: "Scapeler"
date: "1-7-2018"
output: html_document
---

## Hoe werkt het

Kies uit het hoofdmenu (bovenin het scherm) de optie 'Sensor' waarmee de tabs beschikbaar komen om de volgende stappen te doorlopen.

### Stap 1 - Periode selectie
* Omgeving - Kies in dit scherm een omgeving waarin de meetdata opgeslagen zal worden.
* Periode - Kies de start- en einddatum voor de te selecteren meetdata.
* Time series - Kies de interval van de meetdata (per minuut, 5 minuten, uur, dag)

Door de knop 'Selecteer periode' aan te klikken wordt de gekozen omgeving de actieve omgeving. In de actieve omgeving wordt de andere aangegeven parameters (periode, time series) opgeslagen. Tevens wordt deze actieve periode gebruikt voor de volgende stap, het kiezen van de senoren en opvragen van de meetdata.

### Stap 2 - Sensor selectie
* Project - Dit is een voorgeconfigureerde mogelijkheid om sensoren te groeperen per meetsysteem, per stad of per project. Kies hiermee dus een verzameling sensoren. (Later uit te breiden met 'offering' zoals bedoeld in de OGC/SOS standard)
* Unit - Kies de unit of meetkast (OGC/SOS: feature of interest)
* Sensor - Kies de sensor van de unit (OGC/SOS: observable property)

Door de knop 'Selecteer sensor' aan te klikken worden de selectiegegevens opgeslagen in de actieve omgeving én wordt de meetdata opgehaald en ook opgeslagen in deze omgeving.

### Stap 3 - Validatie
Nog niet beschikbaar
In deze stap worden de validatie procedures uitgevoerd. 

### Stap 4 - Kalibratie
Nog niet beschikbaar
In deze stap worden de kalibratie procedures uitgevoerd. 

### Stap 5 - Data samenvatting en sensor data
Onder de tab(s) zijn de gegevens van de verschillende omgevingen in te zien.

### Stap 6 - Plot
Beperkt beschikbaar.
In deze stap worden de resultaten getoond zoals grafieken en plots per omgeving.   

### Stap 7 - Kaart
Nog niet functioneel.
In deze stap worden de resultaten op een kaart getoond.    

